"""
FIT Parser — Enhanced with Gap Handling
Version: 2.0.0-GapAware

NEW FEATURES:
- Intelligent interpolation for sensor dropouts
- Data quality flags per sample
- Gap detection and classification

GAP HANDLING STRATEGY:
  - Gap <10s:   Linear interpolation (sensor glitch)
  - Gap 10-60s: Forward-fill (dropout)
  - Gap >60s:   Mark as UNRELIABLE (exclude from calculations)
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import numpy as np

try:
    import fitparse
    FITPARSE_AVAILABLE = True
except ImportError:
    FITPARSE_AVAILABLE = False


# Quality flags
QUALITY_GOOD = 0
QUALITY_INTERPOLATED = 1  # Gap <10s, linear interpolation
QUALITY_FORWARD_FILLED = 2  # Gap 10-60s, last known value
QUALITY_UNRELIABLE = 3  # Gap >60s, data missing


class ActivityStreamEnhanced:
    """
    Activity stream with data quality tracking.
    
    Field naming convention:
      - Direct physical quantities use unambiguous names: `power`, `heart_rate`,
        `cadence` (no unit suffix — they're conventionally Watts, bpm, rpm)
      - Quantities with non-trivial units keep the suffix: `altitude_m`,
        `distance_m`, `speed_mps`, `temperature_c`
      - Computed/derived booleans (has_power, has_heart_rate, has_rr) and
        aggregates (total_distance_m, total_ascent_m) are properties, not fields
    
    Per-sample arrays (length = n_samples):
        elapsed_s, lat, lon, altitude_m, distance_m,
        power, heart_rate, cadence, speed_mps, temperature_c,
        quality_power, quality_hr, rr_intervals
    
    Scalars:
        n_samples, sport, sub_sport, device_name, start_time,
        total_elapsed_s, gap_summary
    """
    
    def __init__(
        self,
        n_samples: int,
        sport: str = "cycling",
        sub_sport: Optional[str] = None,
        device_name: Optional[str] = None,
        start_time: Optional[datetime] = None,
        total_elapsed_s: Optional[float] = None,
    ):
        self.n_samples = n_samples
        self.sport = sport
        self.sub_sport = sub_sport
        self.device_name = device_name
        self.start_time = start_time
        self.total_elapsed_s = total_elapsed_s
        
        # Time and position
        self.elapsed_s = np.zeros(n_samples, dtype=np.float32)
        self.lat = np.full(n_samples, np.nan, dtype=np.float32)
        self.lon = np.full(n_samples, np.nan, dtype=np.float32)
        self.altitude_m = np.full(n_samples, np.nan, dtype=np.float32)
        self.distance_m = np.zeros(n_samples, dtype=np.float32)
        
        # Core metrics (canonical names — no compat aliases)
        self.power = np.zeros(n_samples, dtype=np.float32)
        self.heart_rate = np.zeros(n_samples, dtype=np.float32)
        self.cadence = np.zeros(n_samples, dtype=np.float32)
        self.speed_mps = np.zeros(n_samples, dtype=np.float32)
        self.temperature_c = np.full(n_samples, np.nan, dtype=np.float32)
        
        # Left/Right pedaling balance (% of total power generated by LEFT leg)
        # NaN when not provided by the sensor. Only meaningful when the source
        # is a dual-side power meter; the parser sets `pedaling_balance_source`
        # to "dual" | "single_estimated" | "unknown" based on device_info.
        self.left_right_balance = np.full(n_samples, np.nan, dtype=np.float32)
        self.pedaling_balance_source: str = "unknown"
        
        # Core body temperature and skin temperature (from CORE sensor)
        # NaN when not provided. core_body_temp is the primary metric (°C),
        # skin_temp is secondary. ambient_temp is from the head unit's
        # built-in thermometer (not from CORE).
        self.core_body_temp = np.full(n_samples, np.nan, dtype=np.float32)
        self.skin_temp = np.full(n_samples, np.nan, dtype=np.float32)
        self.ambient_temp = np.full(n_samples, np.nan, dtype=np.float32)
        self.has_core_sensor: bool = False
        
        # Quality flags
        self.quality_power = np.full(n_samples, QUALITY_GOOD, dtype=np.uint8)
        self.quality_hr = np.full(n_samples, QUALITY_GOOD, dtype=np.uint8)
        
        # RR intervals (per-sample list of beat intervals, may be empty)
        self.rr_intervals: List[List[float]] = [[] for _ in range(n_samples)]
        
        # Gap summary (populated by parser)
        self.gap_summary: Dict[str, Any] = {}
    
    # =========================================================================
    # Computed properties (lightweight — recomputed on access)
    # =========================================================================
    
    @property
    def has_power(self) -> bool:
        return bool(np.any(self.power > 0))
    
    @property
    def has_heart_rate(self) -> bool:
        return bool(np.any(self.heart_rate > 0))
    
    @property
    def has_rr(self) -> bool:
        return any(len(rr) > 0 for rr in self.rr_intervals)
    
    @property
    def total_distance_m(self) -> float:
        if self.distance_m.size == 0:
            return 0.0
        return float(np.nanmax(self.distance_m))
    
    @property
    def total_ascent_m(self) -> Optional[float]:
        if self.altitude_m.size < 2 or np.all(np.isnan(self.altitude_m)):
            return None
        diffs = np.diff(self.altitude_m)
        positives = diffs[diffs > 0]
        return float(np.nansum(positives)) if positives.size else 0.0


def detect_and_fill_gaps(
    values: np.ndarray,
    quality: np.ndarray,
    elapsed: np.ndarray,
    gap_short_s: float = 10.0,
    gap_long_s: float = 60.0,
    zero_is_missing: bool = True,
) -> tuple[np.ndarray, np.ndarray, dict]:
    """
    Detect gaps in data and apply appropriate filling strategy.
    
    Parameters:
        values: Data array (power, HR, etc)
        quality: Quality flags array (modified in-place)
        elapsed: Elapsed time array
        gap_short_s: Threshold for linear interpolation (default 10s)
        gap_long_s: Threshold for unreliable marking (default 60s)
    
    Returns:
        (filled_values, updated_quality, gap_stats)
    
    Gap handling:
        - Missing data (value=0 for power/HR) with dt < gap_short_s \u2192 interpolate
        - Missing data with gap_short_s <= dt < gap_long_s \u2192 forward-fill
        - Missing data with dt >= gap_long_s \u2192 mark unreliable
    """
    n = len(values)
    filled = values.copy()
    
    gaps_detected = []
    gaps_interpolated = 0
    gaps_forward_filled = 0
    gaps_unreliable = 0
    
    # Missing data: 0W power is valid (coasting), 0 bpm HR is not.
    if zero_is_missing:
        missing_mask = (values == 0) | np.isnan(values)
    else:
        missing_mask = np.isnan(values)
    
    if not missing_mask.any():
        return filled, quality, {
            "n_gaps": 0,
            "interpolated": 0,
            "forward_filled": 0,
            "unreliable": 0,
        }
    
    # Detect contiguous gap regions
    i = 0
    while i < n:
        if not missing_mask[i]:
            i += 1
            continue
        
        # Found gap start
        gap_start = i
        while i < n and missing_mask[i]:
            i += 1
        gap_end = i  # exclusive
        
        gap_duration_s = elapsed[gap_end - 1] - (elapsed[gap_start - 1] if gap_start > 0 else 0)
        gap_length = gap_end - gap_start
        
        gaps_detected.append({
            "start_idx": gap_start,
            "end_idx": gap_end,
            "duration_s": gap_duration_s,
            "n_samples": gap_length,
        })
        
        # Apply filling strategy
        if gap_duration_s < gap_short_s:
            # Linear interpolation
            if gap_start > 0 and gap_end < n:
                val_before = filled[gap_start - 1]
                val_after = filled[gap_end]
                interp_vals = np.linspace(val_before, val_after, gap_length + 2)[1:-1]
                filled[gap_start:gap_end] = interp_vals
                quality[gap_start:gap_end] = QUALITY_INTERPOLATED
                gaps_interpolated += 1
            elif gap_start == 0 and gap_end < n:
                # Gap at start \u2192 forward-fill from first valid
                filled[gap_start:gap_end] = filled[gap_end]
                quality[gap_start:gap_end] = QUALITY_FORWARD_FILLED
                gaps_forward_filled += 1
            else:
                # Gap at end \u2192 backward-fill
                filled[gap_start:gap_end] = filled[gap_start - 1]
                quality[gap_start:gap_end] = QUALITY_FORWARD_FILLED
                gaps_forward_filled += 1
        
        elif gap_duration_s < gap_long_s:
            # Forward-fill
            if gap_start > 0:
                filled[gap_start:gap_end] = filled[gap_start - 1]
                quality[gap_start:gap_end] = QUALITY_FORWARD_FILLED
                gaps_forward_filled += 1
            else:
                # Gap at start with no prior value \u2192 mark unreliable
                quality[gap_start:gap_end] = QUALITY_UNRELIABLE
                gaps_unreliable += 1
        
        else:
            # Long gap \u2192 unreliable
            quality[gap_start:gap_end] = QUALITY_UNRELIABLE
            gaps_unreliable += 1
    
    gap_stats = {
        "n_gaps": len(gaps_detected),
        "interpolated": gaps_interpolated,
        "forward_filled": gaps_forward_filled,
        "unreliable": gaps_unreliable,
        "gap_details": gaps_detected if len(gaps_detected) < 50 else gaps_detected[:50],  # Limit size
    }
    
    return filled, quality, gap_stats


def parse_fit_file_enhanced(
    fit_path: str,
    gap_short_s: float = 10.0,
    gap_long_s: float = 60.0,
) -> ActivityStreamEnhanced:
    """
    Parse FIT file with gap detection and intelligent filling.
    
    Parameters:
        fit_path: Path to .fit file
        gap_short_s: Threshold for interpolation (default 10s)
        gap_long_s: Threshold for unreliable marking (default 60s)
    
    Returns:
        ActivityStreamEnhanced with quality flags and gap summary
    """
    if not FITPARSE_AVAILABLE:
        raise RuntimeError("fitparse library not available — install with: pip install fitparse")
    
    fitfile = fitparse.FitFile(fit_path)
    
    # Extract session info
    session_dict = {}
    for rec in fitfile.get_messages("session"):
        for field in rec.fields:
            if field.name == "sport":
                session_dict["sport"] = field.value
            elif field.name == "sub_sport":
                session_dict["sub_sport"] = field.value
            elif field.name == "start_time":
                session_dict["start_time"] = field.value
            elif field.name == "total_elapsed_time":
                session_dict["total_elapsed_time"] = field.value
    
    # Extract device info: head unit is usually the first device_info message,
    # but power meters appear as separate entries with their own manufacturer/product.
    # We also need to classify the power meter as dual-side (real L/R) vs
    # single-side (left-only, balance is estimated and unreliable) vs unknown.
    head_unit_set = False
    pm_source = "unknown"   # default
    
    # Known dual-side power meters (Garmin Vector 3 DUO, Favero Assioma DUO, etc.)
    # Note: identifying dual-side from FIT metadata alone is imperfect. We use
    # product strings as a hint; the most reliable signal is whether balance
    # samples actually vary in the records themselves.
    # Known dual-side power meters (true L/R measurement):
    #   Spider-based: Quarq, Power2Max NG/NGeco, SRM, Shimano FC-R9200-P
    #   Crank-based dual: Rotor 2INpower, Pioneer dual, 4iiii Precision Pro
    #   Pedal-based dual: Garmin Vector 3, Favero Assioma DUO, Rally 200-series,
    #                      Wahoo POWRLINK ZERO (dual), Look/SRM X-Power
    #
    # The marker list catches MANUFACTURER names and common product strings.
    # This is a best-effort heuristic — the data-driven fallback (below)
    # handles any device not in this list.
    _DUAL_MARKERS = (
        # Pedal-based dual
        "vector_3", "assioma_duo", "pedal_uno_duo", "rally_xc200",
        "rally_rs200", "rally_rk200", "garmin_vector_3", "pedal_pair",
        "powrlink_zero_dual", "x-power",
        # Spider-based (manufacturer match)
        "quarq", "power2max", "p2max", "srm",
        # Crank-based dual
        "2inpower", "pioneer", "precision_pro",
        # Generic "duo"/"dual" substring
        "duo", "dual",
    )
    _SINGLE_MARKERS = (
        # Crank-based single (left-only)
        "stages", "4iiii", "precision",  # 4iiii Precision (non-Pro) is single
        # Pedal-based single
        "assioma_uno", "rally_rs100", "rally_rk100", "rally_xc100",
        "powrlink_zero_single",
        # Crank-based single
        "inpower",  # Rotor INpower (single side, not 2INpower)
        # Generic "single"/"uno"/"left" markers
        "single_left", "single_l", "uno", "left_only",
    )
    
    for rec in fitfile.get_messages("device_info"):
        manufacturer = product = None
        ant_dev_type = None
        for field in rec.fields:
            if field.name == "manufacturer":
                manufacturer = field.value
            elif field.name == "garmin_product":
                product = field.value
            elif field.name == "antplus_device_type":
                ant_dev_type = field.value
        
        # First non-empty entry → head unit (typically Garmin Edge)
        if not head_unit_set and (manufacturer or product):
            parts = [str(p) for p in (manufacturer, product) if p]
            session_dict["device_name"] = " ".join(parts)
            head_unit_set = True
            continue
        
        # Subsequent entries: look for power meter
        # ANT+ device type 11 = bike_power (fitparse may return int or string)
        is_power_meter = (
            ant_dev_type in (11, "bike_power")
        ) or (
            manufacturer and any(m in str(manufacturer).lower() for m in (
                "quarq", "favero", "stages", "4iiii", "sram",
            ))
        ) or (
            product and any(m in str(product).lower() for m in (
                "power", "pedal", "crank", "spider", "assioma", "vector",
                "stages", "quarq", "rally", "favero", "4iiii", "p2max"
            ))
        )
        
        if is_power_meter:
            full = f"{manufacturer} {product}".lower() if (manufacturer or product) else ""
            if any(m in full for m in _DUAL_MARKERS):
                pm_source = "dual"
            elif any(m in full for m in _SINGLE_MARKERS):
                pm_source = "single_estimated"
            # else stays "unknown" — we'll let the data itself decide
    
    # Extract record messages
    records = []
    for rec in fitfile.get_messages("record"):
        data = {field.name: field.value for field in rec.fields}
        records.append(data)
    
    if not records:
        raise ValueError("No record messages found in FIT file")
    
    # Convert to enhanced stream
    stream = parse_fit_records_enhanced(
        records,
        session_dict=session_dict,
        gap_short_s=gap_short_s,
        gap_long_s=gap_long_s,
    )
    stream.pedaling_balance_source = pm_source
    
    # Data-driven fallback: if we couldn't identify the power meter from
    # device_info but the FIT contains left_right_balance data that actually
    # VARIES (not all-50 dummy values), then it must be a dual-side meter.
    # This handles any device not in our marker lists, including future models.
    if pm_source == "unknown":
        valid_balance = stream.left_right_balance[~np.isnan(stream.left_right_balance)]
        if len(valid_balance) >= 60:
            # Check if values actually vary (std > 1 means real measurement,
            # not a dummy 50/50 or a constant value from a single-side meter)
            if valid_balance.std() > 1.0:
                stream.pedaling_balance_source = "dual"
            elif np.all(valid_balance == 50) or valid_balance.std() < 0.5:
                # All 50 or near-constant → single-side estimated
                stream.pedaling_balance_source = "single_estimated"
    
    return stream


def parse_fit_records_enhanced(
    records: List[Dict[str, Any]],
    session_dict: Optional[Dict[str, Any]] = None,
    gap_short_s: float = 10.0,
    gap_long_s: float = 60.0,
) -> ActivityStreamEnhanced:
    """
    Parse FIT records into enhanced activity stream with gap handling.
    """
    session_dict = session_dict or {}
    
    sport = session_dict.get("sport", "cycling")
    sub_sport = session_dict.get("sub_sport")
    device_name = session_dict.get("device_name")
    start_time = session_dict.get("start_time")
    total_elapsed = session_dict.get("total_elapsed_time")
    
    # Normalize to 1Hz grid
    if total_elapsed:
        n_samples = int(np.ceil(total_elapsed))
    else:
        # Estimate from records
        if records and "timestamp" in records[0] and "timestamp" in records[-1]:
            dt = (records[-1]["timestamp"] - records[0]["timestamp"]).total_seconds()
            n_samples = int(np.ceil(dt)) + 1
        else:
            n_samples = len(records)
    
    stream = ActivityStreamEnhanced(
        n_samples=n_samples,
        sport=sport,
        sub_sport=sub_sport,
        device_name=device_name,
        start_time=start_time,
        total_elapsed_s=float(n_samples),
    )
    
    # Fill elapsed time grid
    stream.elapsed_s = np.arange(n_samples, dtype=np.float32)
    
    # Map records to 1Hz grid
    for rec in records:
        if "timestamp" not in rec or not start_time:
            continue
        
        elapsed = (rec["timestamp"] - start_time).total_seconds()
        idx = int(np.round(elapsed))
        
        if 0 <= idx < n_samples:
            if "power" in rec and rec["power"] is not None:
                stream.power[idx] = float(rec["power"])
            if "heart_rate" in rec and rec["heart_rate"] is not None:
                stream.heart_rate[idx] = float(rec["heart_rate"])
            if "cadence" in rec and rec["cadence"] is not None:
                stream.cadence[idx] = float(rec["cadence"])
            if "speed" in rec and rec["speed"] is not None:
                stream.speed_mps[idx] = float(rec["speed"])
            if "altitude" in rec and rec["altitude"] is not None:
                stream.altitude_m[idx] = float(rec["altitude"])
            if "distance" in rec and rec["distance"] is not None:
                stream.distance_m[idx] = float(rec["distance"])
            if "position_lat" in rec and rec["position_lat"] is not None:
                stream.lat[idx] = float(rec["position_lat"])
            if "position_long" in rec and rec["position_long"] is not None:
                stream.lon[idx] = float(rec["position_long"])
            if "temperature" in rec and rec["temperature"] is not None:
                stream.temperature_c[idx] = float(rec["temperature"])
                # Standard 'temperature' field is ambient (from head unit sensor).
                # Store it separately for thermal analysis.
                stream.ambient_temp[idx] = float(rec["temperature"])
            
            # CORE body temperature sensor data.
            # Hammerhead/Garmin record these as developer fields with various names.
            # We check all known variants.
            for core_field in ("core_body_temperature", "CoreBodyTemp",
                               "core_temperature", "body_temperature",
                               "core_temp"):
                if core_field in rec and rec[core_field] is not None:
                    try:
                        v = float(rec[core_field])
                        if 30.0 <= v <= 45.0:  # physiological range check
                            stream.core_body_temp[idx] = v
                            stream.has_core_sensor = True
                    except (TypeError, ValueError):
                        pass
                    break
            
            for skin_field in ("skin_temperature", "skin_temp", "SkinTemp"):
                if skin_field in rec and rec[skin_field] is not None:
                    try:
                        v = float(rec[skin_field])
                        if 15.0 <= v <= 45.0:  # physiological range
                            stream.skin_temp[idx] = v
                            stream.has_core_sensor = True
                    except (TypeError, ValueError):
                        pass
                    break
            
            # FIT records may store balance as 'left_right_balance' (raw 0-255) or
            # 'left_pedal_smoothness'/'left_power_phase' from cycling dynamics.
            # Per spec convention: top bit (0x80) flags right-dominant when set,
            # remaining 7 bits give the percent. fitparse normalizes most cases
            # to a plain 0-100 number for the LEFT side; we accept that directly.
            if "left_right_balance" in rec and rec["left_right_balance"] is not None:
                lrb = rec["left_right_balance"]
                try:
                    # Some firmwares emit dicts {"value": int, "right": bool}
                    if isinstance(lrb, dict):
                        v = lrb.get("value")
                        if v is not None:
                            stream.left_right_balance[idx] = float(v)
                    else:
                        v = float(lrb)
                        # If raw 0-255 with top-bit flag, mask and re-interpret
                        if v > 100:
                            v_int = int(v)
                            pct_right = v_int & 0x7F
                            # If top bit set, value is right-percent; else left-percent
                            if v_int & 0x80:
                                stream.left_right_balance[idx] = float(100 - pct_right)
                            else:
                                stream.left_right_balance[idx] = float(pct_right)
                        else:
                            # Already 0-100 (left side), use as-is
                            stream.left_right_balance[idx] = v
                except (TypeError, ValueError):
                    pass
            # RR intervals (HRV-capable devices): list of beat-to-beat ms values
            if rec.get("rr_intervals"):
                rrs = rec["rr_intervals"]
                if isinstance(rrs, (list, tuple)):
                    stream.rr_intervals[idx] = list(rrs)
                else:
                    stream.rr_intervals[idx] = [float(rrs)]
    
    # Detect and fill gaps
    power_filled, quality_p, gap_stats_p = detect_and_fill_gaps(
        stream.power, stream.quality_power, stream.elapsed_s,
        gap_short_s, gap_long_s,
        zero_is_missing=False,  # 0W = coasting, not a sensor dropout
    )
    hr_filled, quality_hr, gap_stats_hr = detect_and_fill_gaps(
        stream.heart_rate, stream.quality_hr, stream.elapsed_s,
        gap_short_s, gap_long_s,
        zero_is_missing=True,   # 0 bpm = sensor dropout
    )
    
    stream.power = power_filled
    stream.quality_power = quality_p
    stream.heart_rate = hr_filled
    stream.quality_hr = quality_hr
    
    stream.gap_summary = {
        "power": gap_stats_p,
        "heart_rate": gap_stats_hr,
    }
    
    return stream


if __name__ == "__main__":
    # Self-test with synthetic data
    print("FIT Parser — Gap Handling Test")
    print("=" * 60)
    
    # Simulate sensor dropout
    n = 300
    power = np.full(n, 200.0)
    power[100:110] = 0  # 10s gap \u2192 interpolate
    power[150:180] = 0  # 30s gap \u2192 forward-fill
    power[250:280] = 0  # 30s gap \u2192 forward-fill
    
    quality = np.full(n, QUALITY_GOOD, dtype=np.uint8)
    elapsed = np.arange(n, dtype=np.float32)
    
    filled, qual, stats = detect_and_fill_gaps(power, quality, elapsed)
    
    print(f"Gaps detected: {stats['n_gaps']}")
    print(f"  Interpolated: {stats['interpolated']}")
    print(f"  Forward-filled: {stats['forward_filled']}")
    print(f"  Unreliable: {stats['unreliable']}")
    print()
    
    print("Sample filled values:")
    print(f"  Before gap [95:105]: {filled[95:105]}")
    print(f"  Quality [95:105]: {qual[95:105]}")
